// <auto-generated />
namespace DataAcces.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class mig_writertitle_edit : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig_writertitle_edit));
        
        string IMigrationMetadata.Id
        {
            get { return "202510031453264_mig_writertitle_edit"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
